version: '3.4'
services:
  backend:
    container_name: trade_paint_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/symfony:/var/www/symfony
    ports:
      - 80:80
    env_file:
      - ./.env
  mysql:
    container_name: trade_paint_mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    env_file:
      - ./.env
  phpmyadmin:
    container_name: trade_paint_phpmyadmin
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    ports:
      - 8080:80
    env_file:
      - ./.env
